[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=node_modules/forge-std/src",
    "@automata-dcap-attestation/=node_modules/automata-dcap-attestation/",
    "@openzeppelin=node_modules/@openzeppelin",
    "@dcap-portal=./"
]

solc = "0.8.27"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "shanghai"

fs_permissions = [{ access = "read-write", path = "./out/deploy" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
